[package]
name = "Lucid-Files"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0.228", features = ["derive"] }
toml = "0.9.8"
walkdir = "2.5.0"
ratatui = { version = "0.28.0", features = ["all-widgets"] }
tachyonfx = "0.20.1"
clap = "4.5.53"
bitflags = "2.10.0"