# ===========================
# File Organiser Configuration
# ===========================

[general]
dry_run = false                 # true / false
confirm_before_action = true    # true / false
overwrite_existing = false      # true / false
remove_empty_dirs = true        # true / false
recursive = true                # true / false
timezone = "UTC"                # UTC,

# ===========================
# Categories
# ===========================

[categories.by_extension] # Key (String) - Value (List of Sting) pair
Audio = ["mp3", "ogg", "wav", "flac", "aac"]
Video = ["mp4", "mkv", "avi", "mov"]
Documents = ["pdf", "docx", "txt", "md"]
Images = ["jpg", "jpeg", "png", "gif", "bmp", "svg"]
Archives = ["zip", "rar", "7z", "tar", "gz"]

[categories.by_size.small]
min = 0
max = 1024

[categories.by_size.medium]
min = 1024
max = 8274


# ===========================
# Filters
# ===========================

[filters]
And = { items = [
    # { Sizes = { min = 0, max = 10024 } },
    # { Extensions = { allowed = ["txt", "mp3"] } },
    # { Or = { items = [

    { Names = { pattern = { Contains = "e" } } },
    { Names = { pattern = { Contains = "Wars" } } }
    #    { Not = { item = { Extensions = { allowed = ["tmp", "bak"] } } } }
    #] } }
] }



# ===========================
# Core Settings
# ===========================
[core]
action = "Move"  # Options: Move, Copy, Delete
scanner = "Recusive"  # Options: Recursive, Simple