# ===========================
# File Organiser Configuration
# ===========================

[general]
dry_run = false
confirm_before_action = true
overwrite_existing = false
remove_empty_dirs = true
recursive = true
timezone = "UTC"

# ===========================
# Categories
# ===========================

[categories.by_extension]
Audio = ["mp3", "ogg", "wav", "flac", "aac"]
Video = ["mp4", "mkv", "avi", "mov"]
Documents = ["pdf", "docx", "txt", "md"]
Images = ["jpg", "jpeg", "png", "gif", "bmp", "svg"]
Archives = ["zip", "rar", "7z", "tar", "gz"]

[categories.by_size.small]
min = 0
max = 1024

[categories.by_size.medium]
min = 1024
max = 8274


# ===========================
# Filters
# ===========================

[filters]
extensions = [".jpg", ".png", ".gif"]
names = [
    { Contains = "backup" },
    { StartsWith = "report" },
    { Equal = "README.md" },
]
sizes = { min = 1024, max = 4096000 }
# dates = { from = "2023-01-01T00:00:00Z", to = "2023-12-31T23:59:59Z" }



# ===========================
# Core Settings
# ===========================
[core]
action = "Move"  # Options: Move, Copy, Delete
scanner = "Recusive"  # Options: Recursive, Simple